try {
    
} catch (err) {
    console.log(err)
}


try {
    
} catch (err) {
    console.log(err)
}finally{

}

throw new Error("this is error")